INSERT INTO position_types (position_name) VALUES ('Propietario/a');
INSERT INTO position_types (position_name) VALUES ('Gerente');
INSERT INTO position_types (position_name) VALUES ('Empleado/a');
INSERT INTO position_types (position_name) VALUES ('Vecino/a');
INSERT INTO position_types (position_name) VALUES ('Hijos');
INSERT INTO position_types (position_name) VALUES ('Padres');
INSERT INTO position_types (position_name) VALUES ('Hermanos');
INSERT INTO position_types (position_name) VALUES ('Suegros');
INSERT INTO position_types (position_name) VALUES ('Tìos');
INSERT INTO position_types (position_name) VALUES ('Amigos');
INSERT INTO position_types (position_name) VALUES ('Sobrinos');
INSERT INTO position_types (position_name) VALUES ('Nuera');
INSERT INTO position_types (position_name) VALUES ('Consuegros');
INSERT INTO position_types (position_name) VALUES ('Nietos');
INSERT INTO position_types (position_name) VALUES ('Yerno');
INSERT INTO position_types (position_name) VALUES ('Cuñados');
INSERT INTO position_types (position_name) VALUES ('Masovero');
INSERT INTO position_types (position_name) VALUES ('Primos');
INSERT INTO position_types (position_name) VALUES ('Encargado/a');
INSERT INTO position_types (position_name) VALUES ('Esposa');
INSERT INTO position_types (position_name) VALUES ('Marido');
INSERT INTO position_types (position_name) VALUES ('Novio/a');
INSERT INTO position_types (position_name) VALUES ('Conserje');
INSERT INTO position_types (position_name) VALUES ('Esposo');
INSERT INTO position_types (position_name) VALUES ('Director/a');
INSERT INTO position_types (position_name) VALUES ('Madre');
INSERT INTO position_types (position_name) VALUES ('Jefe de obra');
INSERT INTO position_types (position_name) VALUES ('Alcalde');
INSERT INTO position_types (position_name) VALUES ('Apoderado/a');
INSERT INTO position_types (position_name) VALUES ('Hermana');
INSERT INTO position_types (position_name) VALUES ('Jefe de Estudios');
INSERT INTO position_types (position_name) VALUES ('Jefe de Administracion');
INSERT INTO position_types (position_name) VALUES ('Asistente social');
INSERT INTO position_types (position_name) VALUES ('Secretario/a');
INSERT INTO position_types (position_name) VALUES ('Jefe de Servicios');
INSERT INTO position_types (position_name) VALUES ('Delegado');
INSERT INTO position_types (position_name) VALUES ('Administrativo/a');
INSERT INTO position_types (position_name) VALUES ('Enologo/a');
INSERT INTO position_types (position_name) VALUES ('Abuelos');
INSERT INTO position_types (position_name) VALUES ('Abuelos');
INSERT INTO position_types (position_name) VALUES ('Mantenimiento');
INSERT INTO position_types (position_name) VALUES ('Permanente');
INSERT INTO position_types (position_name) VALUES ('Coordinador/a');
INSERT INTO position_types (position_name) VALUES ('Alguacil');
INSERT INTO position_types (position_name) VALUES ('Casero');
INSERT INTO position_types (position_name) VALUES ('Casa');
INSERT INTO position_types (position_name) VALUES ('Director/a');
INSERT INTO position_types (position_name) VALUES ('Responsable polideportivo');
INSERT INTO position_types (position_name) VALUES ('Regidor d´ Esports');
INSERT INTO position_types (position_name) VALUES ('Responsable bar');
INSERT INTO position_types (position_name) VALUES ('Regidor Governacio');
INSERT INTO position_types (position_name) VALUES ('Regidora d´Ensenyament');
INSERT INTO position_types (position_name) VALUES ('Regidora de Benestar Social');
INSERT INTO position_types (position_name) VALUES ('Jefe de Producción');
INSERT INTO position_types (position_name) VALUES ('Presidente');
INSERT INTO position_types (position_name) VALUES ('Jefe de area');
INSERT INTO position_types (position_name) VALUES ('Inquilinos');
INSERT INTO position_types (position_name) VALUES ('Jefe de Taller');
INSERT INTO position_types (position_name) VALUES ('Comercial');
INSERT INTO position_types (position_name) VALUES ('Guardia Civil');
INSERT INTO position_types (position_name) VALUES ('Policía Autonómica');
INSERT INTO position_types (position_name) VALUES ('Cuerpo Nacional de Policía');
INSERT INTO position_types (position_name) VALUES ('Otros cuerpos policiales');
INSERT INTO position_types (position_name) VALUES ('Jefe de Estudios');
INSERT INTO position_types (position_name) VALUES ('Jardinero');
INSERT INTO position_types (position_name) VALUES ('Cuidador/a');
INSERT INTO position_types (position_name) VALUES ('Parraco');
INSERT INTO position_types (position_name) VALUES ('Concejal');
INSERT INTO position_types (position_name) VALUES ('Alcaldesa');
INSERT INTO position_types (position_name) VALUES ('Vigilante');
INSERT INTO position_types (position_name) VALUES ('Administrador/a');
INSERT INTO position_types (position_name) VALUES ('Regidor/a');
INSERT INTO position_types (position_name) VALUES ('Supervisor/a');
INSERT INTO position_types (position_name) VALUES ('Jefe de mantenimiento');
INSERT INTO position_types (position_name) VALUES ('Vicepresidente');
INSERT INTO position_types (position_name) VALUES ('Contable');
INSERT INTO position_types (position_name) VALUES ('Director de Tienda');
INSERT INTO position_types (position_name) VALUES ('Ahijada');
INSERT INTO position_types (position_name) VALUES ('Jefe de Ventas');
INSERT INTO position_types (position_name) VALUES ('Teniente Alcalde');
INSERT INTO position_types (position_name) VALUES ('Jefe de operaciones');
INSERT INTO position_types (position_name) VALUES ('Jefe de almacen');
INSERT INTO position_types (position_name) VALUES ('Responsable Auditoria');
INSERT INTO position_types (position_name) VALUES ('Responsable Fabrica');
INSERT INTO position_types (position_name) VALUES ('Trabajador/a');
INSERT INTO position_types (position_name) VALUES ('Responsable de administración');
INSERT INTO position_types (position_name) VALUES ('Subdirector/a');
INSERT INTO position_types (position_name) VALUES ('Recepcion');
INSERT INTO position_types (position_name) VALUES ('Patro');
INSERT INTO position_types (position_name) VALUES ('Responsable equipaments');
INSERT INTO position_types (position_name) VALUES ('Tesorero');
INSERT INTO position_types (position_name) VALUES ('Jefe de Planta');
INSERT INTO position_types (position_name) VALUES ('Bibliotecario');
INSERT INTO position_types (position_name) VALUES ('Ingeniero');
INSERT INTO position_types (position_name) VALUES ('Socio/a');
INSERT INTO position_types (position_name) VALUES ('Jefe estudisos adjunto');
INSERT INTO position_types (position_name) VALUES ('Jefe estudios adjunto ciclos');
INSERT INTO position_types (position_name) VALUES ('Director Regional');
INSERT INTO position_types (position_name) VALUES ('Director Comercial');
INSERT INTO position_types (position_name) VALUES ('Jefe servicios seguridad');
INSERT INTO position_types (position_name) VALUES ('Compañero');
INSERT INTO position_types (position_name) VALUES ('Responsable');
INSERT INTO position_types (position_name) VALUES ('Jefe Almacén');
INSERT INTO position_types (position_name) VALUES ('Adjunto a gerencia');
INSERT INTO position_types (position_name) VALUES ('Jefe de Equipo');
INSERT INTO position_types (position_name) VALUES ('Oficial');
INSERT INTO position_types (position_name) VALUES ('Responsable Operaciones');
INSERT INTO position_types (position_name) VALUES ('Jefe de Sistemas');
INSERT INTO position_types (position_name) VALUES ('logistica');
INSERT INTO position_types (position_name) VALUES ('Director Tecnico');
INSERT INTO position_types (position_name) VALUES ('Director Produccion');
INSERT INTO position_types (position_name) VALUES ('Jefe de tienda');
INSERT INTO position_types (position_name) VALUES ('Jefe Personal');
INSERT INTO position_types (position_name) VALUES ('Encargado Mantenimiento');
INSERT INTO position_types (position_name) VALUES ('Dosificador');
INSERT INTO position_types (position_name) VALUES ('Jefe de Informatica');
INSERT INTO position_types (position_name) VALUES ('Técnico');
INSERT INTO position_types (position_name) VALUES ('Departamento Comunicación');
INSERT INTO position_types (position_name) VALUES ('Asistenta');
INSERT INTO position_types (position_name) VALUES ('Consul');
INSERT INTO position_types (position_name) VALUES ('Agregado');
INSERT INTO position_types (position_name) VALUES ('Agregado');
INSERT INTO position_types (position_name) VALUES ('Monitora');
INSERT INTO position_types (position_name) VALUES ('Aparejador');
INSERT INTO position_types (position_name) VALUES ('Responsable Administración');
INSERT INTO position_types (position_name) VALUES ('Jefe de compras');
INSERT INTO position_types (position_name) VALUES ('Familiar');
INSERT INTO position_types (position_name) VALUES ('Enfermera');
INSERT INTO position_types (position_name) VALUES ('Jefe Planta');
INSERT INTO position_types (position_name) VALUES ('Responsable de Informatica');
INSERT INTO position_types (position_name) VALUES ('Departamento de informatico');
INSERT INTO position_types (position_name) VALUES ('Infermera');
INSERT INTO position_types (position_name) VALUES ('Director Adjunto');
INSERT INTO position_types (position_name) VALUES ('Jefe de laboratorio');
INSERT INTO position_types (position_name) VALUES ('Dpto. proyectos');
INSERT INTO position_types (position_name) VALUES ('Analista');
INSERT INTO position_types (position_name) VALUES ('Directivo');
INSERT INTO position_types (position_name) VALUES ('Responsable seguridad');
INSERT INTO position_types (position_name) VALUES ('Director operaciones');
INSERT INTO position_types (position_name) VALUES ('Responsable Ventas');
INSERT INTO position_types (position_name) VALUES ('Director Financiero');
INSERT INTO position_types (position_name) VALUES ('Delegado Patrimonio');
INSERT INTO position_types (position_name) VALUES ('Director Territorial');
INSERT INTO position_types (position_name) VALUES ('Cap Serveis');
INSERT INTO position_types (position_name) VALUES ('Jefe de seguridad');
INSERT INTO position_types (position_name) VALUES ('Jefe de Postventa');
INSERT INTO position_types (position_name) VALUES ('Jefe Servicios');
INSERT INTO position_types (position_name) VALUES ('Jefe de Obras');
INSERT INTO position_types (position_name) VALUES ('Jefe de Seguridad');
INSERT INTO position_types (position_name) VALUES ('Responsable almacen');
INSERT INTO position_types (position_name) VALUES ('Dependiente/a');
INSERT INTO position_types (position_name) VALUES ('Responsable de compras');
INSERT INTO position_types (position_name) VALUES ('Operario');
INSERT INTO position_types (position_name) VALUES ('Vocal');
INSERT INTO position_types (position_name) VALUES ('Jefe de estudios adjunto');
INSERT INTO position_types (position_name) VALUES ('Inspector');
INSERT INTO position_types (position_name) VALUES ('Jefe de Fabrica');
INSERT INTO position_types (position_name) VALUES ('Director Administrtivo');
INSERT INTO position_types (position_name) VALUES ('Responsable Compras');
INSERT INTO position_types (position_name) VALUES ('Adjunto/a');
INSERT INTO position_types (position_name) VALUES ('Granjero/a');
INSERT INTO position_types (position_name) VALUES ('Responsable Producción');
INSERT INTO position_types (position_name) VALUES ('Vicario');
INSERT INTO position_types (position_name) VALUES ('Vendedora');
INSERT INTO position_types (position_name) VALUES ('Profesor/a');
INSERT INTO position_types (position_name) VALUES ('Notario');
INSERT INTO position_types (position_name) VALUES ('Jefe Instalaciones');
INSERT INTO position_types (position_name) VALUES ('Bodeguero');
INSERT INTO position_types (position_name) VALUES ('RR HH');
INSERT INTO position_types (position_name) VALUES ('Director General');
INSERT INTO position_types (position_name) VALUES ('Arquitecto');
INSERT INTO position_types (position_name) VALUES ('Párroco');
INSERT INTO position_types (position_name) VALUES ('Portero');
INSERT INTO position_types (position_name) VALUES ('Jefa de Recepcion');
INSERT INTO position_types (position_name) VALUES ('Consejero Delegado');
INSERT INTO position_types (position_name) VALUES ('Técnico');
INSERT INTO position_types (position_name) VALUES ('Auxiliar');
INSERT INTO position_types (position_name) VALUES ('Jefe de cajas');
INSERT INTO position_types (position_name) VALUES ('Mensajero');
INSERT INTO position_types (position_name) VALUES ('Tecnico Almacen');
INSERT INTO position_types (position_name) VALUES ('Tecnico comercial');
INSERT INTO position_types (position_name) VALUES ('Cap de estacio');
INSERT INTO position_types (position_name) VALUES ('Gerencia');
INSERT INTO position_types (position_name) VALUES ('Veterinario');
INSERT INTO position_types (position_name) VALUES ('Franquiciado');
INSERT INTO position_types (position_name) VALUES ('Responsable Logística');
INSERT INTO position_types (position_name) VALUES ('Jefe de Parque');
INSERT INTO position_types (position_name) VALUES ('Trabajador/a Social');
INSERT INTO position_types (position_name) VALUES ('Coordinadora Comedor Social');
INSERT INTO position_types (position_name) VALUES ('Director Recambios-Taller');
INSERT INTO position_types (position_name) VALUES ('Responsable de Recambios');
INSERT INTO position_types (position_name) VALUES ('Responsable de Taller');
INSERT INTO position_types (position_name) VALUES ('Encargado Planta');
INSERT INTO position_types (position_name) VALUES ('Encargado Ariestolas');
INSERT INTO position_types (position_name) VALUES ('Sistemas');
INSERT INTO position_types (position_name) VALUES ('Cap d´enginyeria i manteniment');
INSERT INTO position_types (position_name) VALUES ('Cap de manteniment');
INSERT INTO position_types (position_name) VALUES ('Director Laboratorio');
INSERT INTO position_types (position_name) VALUES ('Jefe de policia');
INSERT INTO position_types (position_name) VALUES ('Pareja');
INSERT INTO position_types (position_name) VALUES ('Auditor');
INSERT INTO position_types (position_name) VALUES ('Chófer');
INSERT INTO position_types (position_name) VALUES ('Cajera');
INSERT INTO position_types (position_name) VALUES ('Encargado/a  zona');
INSERT INTO position_types (position_name) VALUES ('Encargado/a sustituto');
INSERT INTO position_types (position_name) VALUES ('Animador/a de caja');
INSERT INTO position_types (position_name) VALUES ('Apoyo zona');
INSERT INTO position_types (position_name) VALUES ('Financiero');
INSERT INTO position_types (position_name) VALUES ('Director Post-Venta');
INSERT INTO position_types (position_name) VALUES ('Director Delegación');
INSERT INTO position_types (position_name) VALUES ('Director Relaciones Laborales');
INSERT INTO position_types (position_name) VALUES ('Accionista');
INSERT INTO position_types (position_name) VALUES ('Consejero');
INSERT INTO position_types (position_name) VALUES ('Controler');
INSERT INTO position_types (position_name) VALUES ('Madre Superiora');
INSERT INTO position_types (position_name) VALUES ('Director IT/IS');
INSERT INTO position_types (position_name) VALUES ('Responsable Tecnico de sistemas');
INSERT INTO position_types (position_name) VALUES ('Responsable Marqueting');
INSERT INTO position_types (position_name) VALUES ('Coordinadora Areas');
INSERT INTO position_types (position_name) VALUES ('Jefe S. Técnico');
INSERT INTO position_types (position_name) VALUES ('Secretario/a Dirección');
INSERT INTO position_types (position_name) VALUES ('Jefe Técnico');
INSERT INTO position_types (position_name) VALUES ('Adjunta 3  Tienda');
INSERT INTO position_types (position_name) VALUES ('Production  manager');
INSERT INTO position_types (position_name) VALUES ('Jefe de Instalaciones');
INSERT INTO position_types (position_name) VALUES ('Director de Fábrica');
INSERT INTO position_types (position_name) VALUES ('Responsable Instalaciones');
INSERT INTO position_types (position_name) VALUES ('Coordinador de Seguridad');
INSERT INTO position_types (position_name) VALUES ('Vice-Consul');
INSERT INTO position_types (position_name) VALUES ('Seminarista');
INSERT INTO position_types (position_name) VALUES ('Cocinero/a');
INSERT INTO position_types (position_name) VALUES ('Masovera');
INSERT INTO position_types (position_name) VALUES ('Hijos Masovera/o');
INSERT INTO position_types (position_name) VALUES ('Cap emergencias');
INSERT INTO position_types (position_name) VALUES ('Responsable Mantenimiento');
INSERT INTO position_types (position_name) VALUES ('Funcionario/a');
INSERT INTO position_types (position_name) VALUES ('Consultor');
INSERT INTO position_types (position_name) VALUES ('Vice-director');
INSERT INTO position_types (position_name) VALUES ('Jefe Oficios');
INSERT INTO position_types (position_name) VALUES ('Director Personal');
INSERT INTO position_types (position_name) VALUES ('Jefe de Oficios');
INSERT INTO position_types (position_name) VALUES ('Guarda');
INSERT INTO position_types (position_name) VALUES ('Jefe Tráfico');
INSERT INTO position_types (position_name) VALUES ('Administración');
INSERT INTO position_types (position_name) VALUES ('Técnico Mantenimiento');
INSERT INTO position_types (position_name) VALUES ('Fitness Manager');
INSERT INTO position_types (position_name) VALUES ('Customer Manager');
INSERT INTO position_types (position_name) VALUES ('Studio Manager');
INSERT INTO position_types (position_name) VALUES ('Pool Manager');
INSERT INTO position_types (position_name) VALUES ('Técnico Fitness');
INSERT INTO position_types (position_name) VALUES ('Técnico Multidisciplinar');
INSERT INTO position_types (position_name) VALUES ('Responsable Nacional Mantenimiento');
INSERT INTO position_types (position_name) VALUES ('Responsable Zona');
INSERT INTO position_types (position_name) VALUES ('Club Manager');
INSERT INTO position_types (position_name) VALUES ('Team Recover');
INSERT INTO position_types (position_name) VALUES ('Fitness');
INSERT INTO position_types (position_name) VALUES ('director Prevención');
INSERT INTO position_types (position_name) VALUES ('Director Mantenimiento');
INSERT INTO position_types (position_name) VALUES ('Regional Mantenimiento');
INSERT INTO position_types (position_name) VALUES ('Customer Service');
INSERT INTO position_types (position_name) VALUES ('Asistant Pool Manager');
INSERT INTO position_types (position_name) VALUES ('Member Care');
INSERT INTO position_types (position_name) VALUES ('Staff Fitness');
INSERT INTO position_types (position_name) VALUES ('Unit Control');
INSERT INTO position_types (position_name) VALUES ('Responsable H&S');
INSERT INTO position_types (position_name) VALUES ('Senior Recepción');
INSERT INTO position_types (position_name) VALUES ('Senior Fitness');
INSERT INTO position_types (position_name) VALUES ('Responsable Atención Cliente');
INSERT INTO position_types (position_name) VALUES ('Responsable Clases Colectivas');
INSERT INTO position_types (position_name) VALUES ('Assistant Manager');
INSERT INTO position_types (position_name) VALUES ('Staff');
INSERT INTO position_types (position_name) VALUES ('Staff / Socorrista');
INSERT INTO position_types (position_name) VALUES ('Manager Mntm Nacional');
INSERT INTO position_types (position_name) VALUES ('2ª Encargado/a');
INSERT INTO position_types (position_name) VALUES ('Fisioterapeuta');
INSERT INTO position_types (position_name) VALUES ('Psicologo/a');
INSERT INTO position_types (position_name) VALUES ('Responsable de Planta');
INSERT INTO position_types (position_name) VALUES ('Técnico de Calidad');
INSERT INTO position_types (position_name) VALUES ('Responsable de Calidad');
INSERT INTO position_types (position_name) VALUES ('Jefe Brigada');
INSERT INTO position_types (position_name) VALUES ('Cap Territori');
INSERT INTO position_types (position_name) VALUES ('Mecanico');
INSERT INTO position_types (position_name) VALUES ('Operaciones');
INSERT INTO position_types (position_name) VALUES ('Jefe de Sala');
INSERT INTO position_types (position_name) VALUES ('Store Manager');
INSERT INTO position_types (position_name) VALUES ('Assistant Manager');
INSERT INTO position_types (position_name) VALUES ('General Manager');
INSERT INTO position_types (position_name) VALUES ('Empleado Producción');
INSERT INTO position_types (position_name) VALUES ('Responsable Tienda');
INSERT INTO position_types (position_name) VALUES ('Manager Tienda');
INSERT INTO position_types (position_name) VALUES ('Lider Tienda');
INSERT INTO position_types (position_name) VALUES ('Responsable Obra');
INSERT INTO position_types (position_name) VALUES ('Gerente Seguridad');
INSERT INTO position_types (position_name) VALUES ('Director Seguridad');
INSERT INTO position_types (position_name) VALUES ('Director/a  RRHH');
INSERT INTO position_types (position_name) VALUES ('Educadora');
INSERT INTO position_types (position_name) VALUES ('Co-Lider tienda');
INSERT INTO position_types (position_name) VALUES ('Responsable Turno');
INSERT INTO position_types (position_name) VALUES ('Responsable Plataforma');
INSERT INTO position_types (position_name) VALUES ('Gestor Técnico');
INSERT INTO position_types (position_name) VALUES ('Gerente B');
INSERT INTO position_types (position_name) VALUES ('Director Corporativo');
INSERT INTO position_types (position_name) VALUES ('Capataz');
INSERT INTO position_types (position_name) VALUES ('Gestor de Clientes');
INSERT INTO position_types (position_name) VALUES ('Responsable Regional');
INSERT INTO position_types (position_name) VALUES ('Manager Studios');
INSERT INTO position_types (position_name) VALUES ('Gestor Comercial Externo');
INSERT INTO position_types (position_name) VALUES ('Responsable Servicios');
INSERT INTO position_types (position_name) VALUES ('Técnico Seguridad');
INSERT INTO position_types (position_name) VALUES ('Representante');
INSERT INTO position_types (position_name) VALUES ('Regional Manager');
INSERT INTO position_types (position_name) VALUES ('Visual');
INSERT INTO position_types (position_name) VALUES ('Secretario Provincial');
INSERT INTO position_types (position_name) VALUES ('Manager Mntm Regional');
INSERT INTO position_types (position_name) VALUES ('Aspirante cargo');
INSERT INTO position_types (position_name) VALUES ('Líder de zona');
INSERT INTO position_types (position_name) VALUES ('Responsable Trafico');
INSERT INTO position_types (position_name) VALUES ('Directora  de Tiendas');
INSERT INTO position_types (position_name) VALUES ('Jefe Seccion');
INSERT INTO position_types (position_name) VALUES ('Agente Medio Ambiental');
INSERT INTO position_types (position_name) VALUES ('Abogado/a');
INSERT INTO position_types (position_name) VALUES ('Responsable CPD');
INSERT INTO position_types (position_name) VALUES ('Gerente A+');
INSERT INTO position_types (position_name) VALUES ('Coordinador de planta');
INSERT INTO position_types (position_name) VALUES ('Director Sistemas');
INSERT INTO position_types (position_name) VALUES ('Interventor');
INSERT INTO position_types (position_name) VALUES ('Manager Area');
INSERT INTO position_types (position_name) VALUES ('Director Explotación');
INSERT INTO position_types (position_name) VALUES ('Ceo');
