INSERT INTO provinces (name) VALUES ('A CORUÑA');
INSERT INTO provinces (name) VALUES ('ALAVA');
INSERT INTO provinces (name) VALUES ('ALBACETE');
INSERT INTO provinces (name) VALUES ('ALICANTE');
INSERT INTO provinces (name) VALUES ('ALMERIA');
INSERT INTO provinces (name) VALUES ('ASTURIAS');
INSERT INTO provinces (name) VALUES ('AVILA');
INSERT INTO provinces (name) VALUES ('BADAJOZ');
INSERT INTO provinces (name) VALUES ('BARCELONA');
INSERT INTO provinces (name) VALUES ('BIZKAIA');
INSERT INTO provinces (name) VALUES ('BURGOS');
INSERT INTO provinces (name) VALUES ('CACERES');
INSERT INTO provinces (name) VALUES ('CADIZ');
INSERT INTO provinces (name) VALUES ('CANTABRIA');
INSERT INTO provinces (name) VALUES ('CASTELLON');
INSERT INTO provinces (name) VALUES ('CEUTA');
INSERT INTO provinces (name) VALUES ('CIUDAD REAL');
INSERT INTO provinces (name) VALUES ('CORDOBA');
INSERT INTO provinces (name) VALUES ('CUENCA');
INSERT INTO provinces (name) VALUES ('GIPUZKOA');
INSERT INTO provinces (name) VALUES ('GIRONA');
INSERT INTO provinces (name) VALUES ('GRANADA');
INSERT INTO provinces (name) VALUES ('GUADALAJARA');
INSERT INTO provinces (name) VALUES ('HUELVA');
INSERT INTO provinces (name) VALUES ('HUESCA');
INSERT INTO provinces (name) VALUES ('ILLES BALEARS');
INSERT INTO provinces (name) VALUES ('JAEN');
INSERT INTO provinces (name) VALUES ('LA RIOJA');
INSERT INTO provinces (name) VALUES ('LAS PALMAS');
INSERT INTO provinces (name) VALUES ('LEON');
INSERT INTO provinces (name) VALUES ('LLEIDA');
INSERT INTO provinces (name) VALUES ('LUGO');
INSERT INTO provinces (name) VALUES ('MADRID');
INSERT INTO provinces (name) VALUES ('MALAGA');
INSERT INTO provinces (name) VALUES ('MELILLA');
INSERT INTO provinces (name) VALUES ('MURCIA');
INSERT INTO provinces (name) VALUES ('NAVARRA');
INSERT INTO provinces (name) VALUES ('OURENSE');
INSERT INTO provinces (name) VALUES ('PALENCIA');
INSERT INTO provinces (name) VALUES ('PONTEVEDRA');
INSERT INTO provinces (name) VALUES ('SALAMANCA');
INSERT INTO provinces (name) VALUES ('SANTA CRUZ DE TENERIFE');
INSERT INTO provinces (name) VALUES ('SEGOVIA');
INSERT INTO provinces (name) VALUES ('SEVILLA');
INSERT INTO provinces (name) VALUES ('SORIA');
INSERT INTO provinces (name) VALUES ('TARRAGONA');
INSERT INTO provinces (name) VALUES ('TERUEL');
INSERT INTO provinces (name) VALUES ('TOLEDO');
INSERT INTO provinces (name) VALUES ('VALENCIA');
INSERT INTO provinces (name) VALUES ('VALLADOLID');
INSERT INTO provinces (name) VALUES ('ZAMORA');
INSERT INTO provinces (name) VALUES ('ZARAGOZA');
